main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.home, name='home'),
    # path('', views.about, name='about'),
    path('', views.cities_index, name='cities_index'),
    path('cities/<int:city_id>/', views.city_detail, name='city_detail'),
    path('cities/create/', views.CityCreate.as_view(), name='city_create'),
    path('cities/<int:pk>/update/', views.CityUpdate.as_view(), name='city_update'),
    path('cities/<int:pk>/delete/', views.CityDelete.as_view(), name='city_delete'),
    path('experiences/', views.experiences_index, name='experiences_index'),
    path('experiences/<int:experience_id>/', views.experience_detail, name='experience_detail'),
    path('experiences/create/', views.experiences_create, name='experience_create'),
    path('experiences/<int:pk>/update/', views.ExperienceUpdate.as_view(), name='experience_update'),
    path('experiences/<int:pk>/delete/', views.ExperienceDelete.as_view(), name='experience_delete'),
    path('cities/<int:city_id>/add_photo/', views.add_photo, name='add_photo'),
    path('search/', views.search, name="search"),
    path('accounts/signup/', views.signup, name='signup'),
]

travelguide/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=100)
    population = models.IntegerField()
    languages = models.TextField(max_length=250)
    currency = models.CharField(max_length=3)
    imagelink = models.CharField(max_length=100)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('citydetail', kwargs={'city_id': self.id})


class Experiences(models.Model):
    eventname = models.CharField(max_length=100)
    eventdate = models.DateField()
    eventtime = models.TimeField()
    address = models.TextField(max_length=250)
    eventdescription = models.TextField(max_length=500)
    eventlink = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.eventname

    def get_absolute_url(self):
        return reverse('experiencedetail', kwargs={'experience_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for city_id {self.city_id} @{self.url}"

main_app/forms.py
from django import forms
from .models import City, Experiences


class ExperiencesForm(forms.ModelForm):
    class Meta:
        model = Experiences
        fields = ['eventname', 'eventdate', 'eventtime', 'address','eventdescription', 'eventlink', 'city', 'user']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.all()

    #     eventname = models.CharField(max_length=100)
    # eventdate = models.DateField()
    # eventtime = models.TimeField()
    # address = models.TextField(max_length=250)
    # eventdescription = models.TextField(max_length=500)
    # eventlink = models.CharField(max_length=100)
    # city = models.ForeignKey(City, on_delete=models.CASCADE)

main_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ExperiencesForm
from .models import City, Experiences, Photo
import uuid
import boto3
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


S3_BASE_URL = 'https://s3.ca-central-1.amazonaws.com/'
BUCKET = 'travelguide1'


class CityCreate(LoginRequiredMixin, CreateView):
    model = City
    fields = '__all__'
    success_url = '/'


class CityUpdate(LoginRequiredMixin, UpdateView):
    model = City
    # Disallowing the renaming of a city by excluding the name field
    fields = ['population', 'languages', 'currency']
    success_url = '/'


class CityDelete(LoginRequiredMixin, DeleteView):
    model = City
    success_url = '/'


class ExperienceUpdate(LoginRequiredMixin, UpdateView):
    model = Experiences
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['eventname', 'eventdate', 'eventtime', 'address', 'eventdescription',
              'eventlink', 'city']
    success_url = '/experiences/'


class ExperienceDelete(LoginRequiredMixin, DeleteView):
    model = Experiences
    success_url = '/experiences/'

# class ExperienceCreate(CreateView):
#   model = Experiences
#   fields = '__all__'
#   form = ExperiencesForm
#   success_url = '/experiences/'


@login_required
def experiences_create(request):
    if request.method == 'POST':
        form = ExperiencesForm(request.POST)
        form.save()
        return redirect('/experiences/')
    form = ExperiencesForm()
    return render(request, 'main_app/experiences_form.html', {'form': form})


def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
    return super().form_valid(form)


# def home(request):
#     return HttpResponse('<h1>made a change here Hello here it is /ᐠ｡‸｡ᐟ\ﾉ</h1>')


def about(request):
    return render(request, 'about.html')


def cities_index(request):
    cities = City.objects.all()
    return render(request, 'about.html', {'cities': cities})


def city_detail(request, city_id):
    city = City.objects.get(id=city_id)
    return render(request, 'cities/citydetail.html', {'city': city})


def experiences_index(request):
    experiences = Experiences.objects.all()
    return render(request, 'experiences/index.html', {'experiences': experiences})


def experience_detail(request, experience_id):
    experience = Experiences.objects.get(id=experience_id)
    return render(request, 'experiences/experiencedetail.html', {'experience': experience})


@login_required
def add_photo(request, city_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, city_id=city_id)
            photo.save()
        except Exception as e:
            print(e)
            print('x-----error above-----x')

    return redirect('city_detail', city_id=city_id)

def search(request):
    cities = City.objects.all()
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            cities = cities.filter(name__icontains=keyword)
    
    data = {
        'cities': cities
    }
    return render(request, 'search.html', data)




def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('/')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)
# class City:  # Note that parens are optional if not inheriting from another class
#   def __init__(self, name, population, languages, currency):
#     self.name = name
#     self.population = population
#     self.languages = languages
#     self.currency = currency

# cities = [
#   City('London', 1400000,'English', 'GBP'),
#   City('New Delhi', 10000000, 'Hindi', 'INR'),
#   City('Paris', 25000000, 'French', 'EUR')
# ]

main_app/templates/about.html
    {% extends 'base.html' %}
    {% block content %}
    <h1>Welcome to J&A Travel Guide</h1>
    <p class="flow-text">Pick your city and generate your unique destination with J&A Travel Guide</p>

    {% for city in cities %}
    <div class="index-banner color2">
        <div class="section">
            <div class="row">
                <div class="col s6 m12">
                    <div class="card">
                        <div class="card-image">
                            <img
                                src="{{city.imagelink}}">
                            <span class="card-title">{{ city.name }}</span>
                            <a href="{% url 'city_detail' city.id %}" class="btn-floating halfway-fab waves-effect waves-light red"><i
                                    class="material-icons">GO</i></a>
                        </div>
                        <div class="card-content">
                            <p>Card Description</p>
                        </div>
                    </div>

                   
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% endblock %}
    

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>J&A Travel Guide</title>
  <!-- Materialize CSS CDN Link to be uncommented later -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

</head>

<body>
  <header class="navbar-fixed">
    <nav class="light-blue darken-4">
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;J&A Travel Guide</a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="right">
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        </ul>
        {% else %}
        <ul class="right">
          <li><a href="{% url 'login' %}">Log In</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        </ul>
        {% endif %}
        
        <ul class="right">
          <li><a href="/experiences">Experiences</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'cities_index' %}">Home</a></li>
        </ul>
       
        

      </div>

    </nav>
  </header>
  <main class="container">

    {% block content %}
    {% endblock %}
  </main>

  <footer class="light-blue darken-4">
    <footer class="page-footer">
      <div class="right">All Rights Reserved, &copy; 2022 J&A &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/cities/citydetail.html
{% extends 'base.html' %}
{% block content %}

<h1>City Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ city.name }}</span>
        <p>Population: {{ city.population }}</p>
        <p>Languages: {{ city.languages }}</p>
        <p>Currency: {{ city.currency }}</p>
        <!-- {% if user.is_authenticated %}
        <div class="card-action">
          <a href="{% url 'city_update' city.id %}">Edit</a>
          <a href="{% url 'city_delete' city.id %}">Delete</a>
        </div>
        {% endif %} -->
      </div>
    </div>
  </div>

  {% if user.is_authenticated %}
  <a class="btn" href="{% url 'experience_create' %}">Add a new Experience</a>
  {% endif %}
  <div class="col s6">
    <table class="card">
      <thead>
        <tr>
          <th>Event Date</th>
          <th>Event Name</th>
        </tr>
      </thead>
      <tbody>
        {% for experiences in city.experiences_set.all %}
        <tr>
          <td>{{experiences.eventdate}}</td>
          <td>{{experiences.eventname}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>

</div>
<!-- Insert photo markup below this comment -->

{% for photo in city.photo_set.all %}
<img class="responsive-img card-panel" src="{{photo.url}}">
{% empty %}
<div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}

<!-- new code below -->
{% if user.is_authenticated %}
<form action="{% url 'add_photo' city.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
  {% csrf_token %}
  <input type="file" name="photo-file">
  <br><br>
  <input type="submit" class="btn" value="Upload Photo">
</form>
{% endif %}

{% endblock %}

main_app/templates/cities/index.html
<!-- {% extends 'base.html' %}
{% block content %}

<h2>Cities List</h2>
{% if user.is_authenticated %}
<a class="btn" href="{% url 'city_create' %}">Add a City</a>
{% endif %}
{% for city in cities %}
<div class="card">
  <a href="{% url 'city_detail' city.id %}">
    <div class="card-content">
      <span class="card-title">{{ city.name }}</span>
       <p>Population: {{ city.population }}</p>
      <p>Languages: {{ city.languages }}</p>
      <p>Currency: {{ city.currency }}</p> -->
    </div>
  </a>
</div>

<!-- {% endfor %}
{% endblock %} --> 

main_app/templates/experiences/experiencedetail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ experience.eventname }} details</h1>
<div class="row">
  <div>
    <div>
      <div>
        <!-- <span class="card-title">{{ experience.eventname }}</span> -->
        <p>Event Date: {{ experience.eventdate }}</p>
        <p>Event Time: {{ experience.eventtime }}</p>
        <p>Address: {{ experience.address }}</p>
        <p>Event Description: {{ experience.eventdescription }}</p>
        <p>Event link: {{ experience.eventlink }}</p>
        <p>City: {{ experience.city }}</p>
        {% if user.is_authenticated %}
        <div class="card-action">
          <a class="btn" href="{% url 'experience_update' experience.id %}">Edit</a>
          <a class="btn" href="{% url 'experience_delete' experience.id %}">Delete</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- <div class="col s6">
    <table class="card">
      <thead>
        <tr>
          <th>Event Date</th>
          <th>Event Name</th>
        </tr>
      </thead>
      <tbody>
        {% for experiences in city.experiences_set.all %}
        <tr>
          <td>{{experiences.eventdate}}</td>
          <td>{{experiences.eventname}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div> -->

</div>




{% endblock %}

main_app/templates/experiences/index.html
{% extends 'base.html' %}
{% block content %}

<h2>Experiences List</h2>
{% if user.is_authenticated %}
<a class="btn" href="{% url 'experience_create' %}">Add a new Experience</a>
{% endif %}
<br>
{% for experience in experiences %}
  <div class="card">
      <a href="{% url 'experience_detail' experience.id %}">
    <div class="card-content">
      <span class="card-title">{{experience.eventname}}</span>
      <!-- <p>Population: {{ city.population }}</p>
      <p>Languages: {{ city.languages }}</p>
      <p>Currency: {{ city.currency }}</p> -->
    </div>
      </a>
  </div>
{% endfor %}
{% endblock %}

main_app/templates/main_app/city_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete City</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'city_detail' city.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/city_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add a new City</h1>
{% endif %}
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/experiences_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Experience</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'experience_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/experiences_form.html
<style>
    select {
        display: block !important;
    }
</style>
{% extends 'base.html' %}

{% block content %}
  <h2>Add a new Experience</h2>
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <!-- <table>
      Render the inputs inside of <tr>s & <td>s
      {{ form.as_table }}
    </table> -->
    {{form}}
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/search.html
{% extends 'base.html' %}
{% block content %}

{% for city in cities %}
    <div class="index-banner color2">
        <div class="section">
            <div class="row">
                <div class="col s6 m12">
                    <div class="card">
                        <div class="card-image">
                            <img
                                src="{{city.imagelink}}">
                            <span class="card-title">{{ city.name }}</span>
                            <a href="{% url 'city_detail' city.id %}" class="btn-floating halfway-fab waves-effect waves-light red"><i
                                    class="material-icons">GO</i></a>
                        </div>
                        <!-- <div class="card-content">
                            <p>Card Description</p>
                        </div> -->
                    </div>

                    {% endfor %}
{% endblock %}